name: printing hello world

on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]
jobs:
  print_hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run echo command
        run: |
          echo "Hello world"