name: printing hello world

on:
  push:
    branches: [ main ]
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run echo command
        run: echo "Hello world"