name: Running shell script
run-name: Running shell script 

on:
  push:
    branches: [ main ]

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: print present working directory
        run: pwd
      - name: run ls command
        run: ls
      - name: Running script
        run: bash shell-script.sh
