name: Running shell script
run-name: Running shell script 

on:
  push:
    branches: [ main ]

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: running shell script
        run: pwd
        run: ls
