name: Use variables
run-name: Use of variables in github actions
on:
  push:
    branches: [ main ]

jobs:
  step-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Create and print step level env vars 
        env:
          DEPT: marketing
          ORG: CloudEQ
        run: echo "This is $DEPT from $ORG Organization"
  job-env-var:
    runs-on: ubuntu-latest
    env:
      jobNum: 2
      DEPT: Sales
      ORG: CloudEQ
    steps:
      - name: Create and Print job level env vars ${{ jobNum }}.
        run: echo "This is $DEPT from $ORG Organization"

