name: Use variables
run-name: Use of variables in github actions
env:
  workflow-num: 4
on:
  push:
    branches: [ main ]

jobs:
# job to print workflow level variables
  workflow-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Pring workflow level env variables ${{ env.workflow-num }} 
        run: echo "This is workflow number $workflow-num"
# job to print step level variables
  step-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Create and print step level env vars 
        env:
          DEPT: marketing
          ORG: CloudEQ
        run: echo "This is $DEPT from $ORG Organization"
# job to print job level variables
  job-env-var:
    runs-on: ubuntu-latest
    env:
      jobnum: 2
      DEPT: Sales
      ORG: CloudEQ
    steps:
      - name: Create and Print job level env vars ${{ env.jobnum }}.
        run: echo "This is $DEPT from $ORG Organization"

