name: workflow 2 install node js 14 and install bat npm package
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-node@v3
        with:
          node-version: '14'
      - run: npm install bats
      - run: bats -v